name: Hacktribe
path: ./ht_data
midi:
  input: electribe2 sampler:electribe2 sampler electribe2 s
  output: electribe2 sampler:electribe2 sampler electribe2 s
  control:
    input:
      -
    map: ./midi_map.py
log:
  level: error
